StartupCentral/Models/Startupbs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Data.Entity.Infrastructure;
using System.Threading.Tasks;

namespace StartupCentral.Models
{
    //[Table("Startupbs")]
    public class Startupbs
    {
        public Startupbs()
        {
            this.Contatos = new HashSet<Contato>();
            this.Observacoes = new List<Observacoes>();
        }


        [Key]
        public int StartupbsId { get; set; }

        [Required(ErrorMessage = "Nome não pode ser branco."), Display(Name = "Nome*")]
        public string Nome { get; set; }

        [Display(Name = "Email*")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name = "Microsoft Account*")]
        public string MicrosoftAccount { get; set; }

        [Display(Name = "BizSpark ID")]
        public string BizSparkID { get; set; }

        public virtual ICollection<Contato> Contatos { get; set; }

        [Display(Name = "Benefício")]
        public int BeneficioId { get; set; }

        public virtual Beneficio Beneficio { get; set; }

        [Display(Name = "Aceleradora")]
        public int AceleradoraId { get; set; }

        public virtual Aceleradora Aceleradora { get; set; }

        [Display(Name = "Status")]
        public int StatusId { get; set; }

        public virtual Status Status { get; set; }


        [Display(Name = "Consumo do Mês"), DataType(DataType.Currency)]
        public decimal ConsumoMes { get; set; }


        [Display(Name = "Consumo Acumulado do Ano"), DataType(DataType.Currency)]
        public decimal ConsumoAcumulado { get; set; }

        [Display(Name = "Consumo Pago"), DataType(DataType.Currency)]
        public decimal ConsumoPago { get; set; }

        [Display(Name = "Observações | Comentários")]
        [StringLength(120)]
        public virtual ICollection<Observacoes> Observacoes { get; set; }

        public string Owner { get; set; }
    }

    public class StartupDBContext : DbContext
    {
        public DbSet<Startupbs> Startup { get; set; }
        public DbSet<Aceleradora> Aceleradora { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Endereco> Endereço { get; set; }
        public DbSet<Contato> Contato { get; set; }
        public DbSet<Beneficio> Benefício { get; set; }
        public DbSet<LogLogin> LogLogin { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<GeneralLog> GeneralLogs { get; set; }
        public DbSet<Log> logs { get; set; }
        public DbSet<Observacoes> Observacoes { get; set; }

        public StartupDBContext()
        {
            //Database.SetInitializer(new DropCreateDatabaseIfModelChanges<StartupDBContext>());
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Conventions.Remove<ManyToManyCascadeDeleteConvention>();
            modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
            modelBuilder.Conventions.Remove<OneToOneConstraintIntroductionConvention>();

            modelBuilder.Entity<Observacoes>().
                HasRequired<Startupbs>(s => s.Startupbs).
                WithMany(s => s.Observacoes);

            modelBuilder.Entity<Observacoes>().
                HasRequired<Aceleradora>(s => s.Aceleradora).
                WithMany(s => s.Observacoes);

            modelBuilder.Entity<Startupbs>().
                HasRequired<Aceleradora>(s => s.Aceleradora).
                WithMany(s => s.Startups);

            base.OnModelCreating(modelBuilder);
        }

        public override Task<int> SaveChangesAsync()
        {
            // Detecta as alterações existentes na instância corrente do DbContext.
            this.ChangeTracker.DetectChanges();
            // Identifica as entidades que devem gerar registros em log.
            var entries = DetectEntries();
            // Cria lista para armazenamento temporário dos registros em log.
            List<Log> logs = new List<Log>(entries.Count());
            // Varre as entidades que devem gerar registros em log.
            foreach (var entry in entries)
            {
                // Cria novo registro de log.
                Log newLog = GetLog(entry);

                if (newLog != null)
                    logs.Add(newLog);
            }
            // Adiciona os registros de log na fonte de dados.
            foreach (var item in logs)
            {
                this.Entry(item).State = EntityState.Added;
            }
            // Persiste as informações na fonte de dados.
            return base.SaveChangesAsync();
        }

        /// <summary>
        /// Identifica quais entidades devem ser gerar registros de log.
        /// </summary>
        private IEnumerable<DbEntityEntry> DetectEntries()
        {
            return ChangeTracker.Entries().Where(e => (e.State == EntityState.Modified ||
                                                        e.State == EntityState.Added ||
                                                        e.State == EntityState.Deleted) &&
                                                        e.Entity.GetType() != typeof(Log) &&
                                                        e.Entity.GetType() != typeof(GeneralLog) &&
                                                        e.Entity.GetType() != typeof(LogLogin));
        }

        /// <summary>
        /// Cria os registros de log.
        /// </summary>
        private Log GetLog(DbEntityEntry entry)
        {

            Log returnValue = null;

            if (entry.State == EntityState.Added)
            {
                returnValue = GetInsertLog(entry);
            }
            else if (entry.State == EntityState.Modified)
            {
                returnValue = GetUpdateLog(entry);
            }
            else if (entry.State == EntityState.Deleted)
            {
                returnValue = GetDeleteLog(entry);
            }

            return returnValue;
        }

        private Log GetInsertLog(DbEntityEntry entry)
        {

            return Log.CreateInsertLog(entry.Entity);
        }

        private Log GetDeleteLog(DbEntityEntry entry)
        {

            return Log.CreateDeleteLog(entry.Entity);
        }

        private Log GetUpdateLog(DbEntityEntry entry)
        {

            object originalValue = null;

            if (entry.OriginalValues != null)
                originalValue = entry.OriginalValues.ToObject();
            else
                originalValue = entry.GetDatabaseValues().ToObject();

            return Log.CreateUpdateLog(originalValue, entry.Entity);
        }
    }
}

StartupCentral/Controllers/StartupbsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StartupCentral.Models;
using System.Security.Claims;
using Excel = Microsoft.Office.Interop.Excel;
using System.IO;
using System.ComponentModel;

namespace StartupCentral.Controllers
{
    public class StartupbsController : Controller
    {
        private StartupDBContext db = new StartupDBContext();
        User user = HomeController.userlogged;

        // GET: Startupbs
        public async Task<ActionResult> Index()
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            var startup = db.Startup.Include(s => s.Aceleradora).Include(s => s.Beneficio).Include(s => s.Status).Include(s=>s.Contatos);
            return View(await startup.ToListAsync());
        }

        [HttpPost]
        //Overwrite with search
        public async Task<ActionResult> Index(string id)
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            var SearchString = Request.Form[0];
            var startups = db.Startup.Include(s => s.Aceleradora).Include(s => s.Beneficio).Include(s => s.Status).Include(s => s.Contatos).Where(s=>s.Nome.Contains(SearchString));
            return View(await startups.ToListAsync());
        }

        // GET: Startupbs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            List<Contato> lc = (from c in db.Contato where c.Startup.Any(s => s.StartupbsId == id) select c).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Startupbs startupbs = await db.Startup.FindAsync(id);
            db.GeneralLogs.Add(new GeneralLog { Datetime = DateTime.Now, Action = UserAction.Consultou, ObjectUsed = startupbs.Nome, UserId = db.User.Where(u => u.email == user.email).FirstOrDefault().UserId });
            await db.SaveChangesAsync();
            startupbs.Contatos = lc;
            if (startupbs == null)
            {
                return HttpNotFound();
            }
            return View(startupbs);
        }

        // GET: Startupbs/Create
        public ActionResult Create()
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            ViewBag.AceleradoraId = new SelectList(db.Aceleradora, "AceleradoraId", "Nome");
            ViewBag.BeneficioId = new SelectList(db.Benefício, "BeneficioId", "Nome");
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Nome");
            return View();
        }

        // POST: Startupbs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StartupbsId,Nome,Email,MicrosoftAccount,Contatos,BizSparkID,BeneficioId,AceleradoraId,StatusId,ConsumoMes,ConsumoAcumulado,ConsumoPago,Observacoes,Owner")] Startupbs startupbs)
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            if (ModelState.IsValid)
            {
                db.Startup.Add(startupbs);
                await db.SaveChangesAsync();
                db.GeneralLogs.Add(new GeneralLog { Datetime = DateTime.Now, Action = UserAction.Salvou, ObjectUsed = startupbs.Nome, UserId = db.User.Where(u => u.email == user.email).FirstOrDefault().UserId });
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AceleradoraId = new SelectList(db.Aceleradora, "AceleradoraId", "Nome", startupbs.AceleradoraId);
            ViewBag.BeneficioId = new SelectList(db.Benefício, "BeneficioId", "Nome", startupbs.BeneficioId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Nome", startupbs.StatusId);
            return View(startupbs);
        }

        // GET: Startupbs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            List<Contato> lc = (from c in db.Contato where c.Startup.Any(s => s.StartupbsId == id) select c).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Startupbs startupbs = await db.Startup.FindAsync(id);
            if (startupbs == null)
            {
                return HttpNotFound();
            }
            startupbs.Contatos = lc;
            ViewBag.AceleradoraId = new SelectList(db.Aceleradora, "AceleradoraId", "Nome", startupbs.AceleradoraId);
            ViewBag.BeneficioId = new SelectList(db.Benefício, "BeneficioId", "Nome", startupbs.BeneficioId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Nome", startupbs.StatusId);
            return View(startupbs);
        }

        // POST: Startupbs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "StartupbsId,Nome,Email,MicrosoftAccount,BizSparkID,BeneficioId,Contatos,AceleradoraId,StatusId,ConsumoMes,ConsumoAcumulado,ConsumoPago,Observacoes,Owner")] Startupbs startupbs)
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            if (ModelState.IsValid)
            {
                db.Entry(startupbs).State = EntityState.Modified;
                await db.SaveChangesAsync();
                db.GeneralLogs.Add(new GeneralLog { Datetime = DateTime.Now, Action = UserAction.Editou, ObjectUsed = startupbs.Nome, UserId = db.User.Where(u => u.email == user.email).FirstOrDefault().UserId });
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AceleradoraId = new SelectList(db.Aceleradora, "AceleradoraId", "Nome", startupbs.AceleradoraId);
            ViewBag.BeneficioId = new SelectList(db.Benefício, "BeneficioId", "Nome", startupbs.BeneficioId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Nome", startupbs.StatusId);
            return View(startupbs);
        }

        // GET: Startupbs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Startupbs startupbs = await db.Startup.FindAsync(id);
            if (startupbs == null)
            {
                return HttpNotFound();
            }
            return View(startupbs);
        }

        // POST: Startupbs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Startupbs startupbs = await db.Startup.FindAsync(id);
            db.Startup.Remove(startupbs);
            await db.SaveChangesAsync();
            db.GeneralLogs.Add(new GeneralLog { Datetime = DateTime.Now, Action = UserAction.Deletou, ObjectUsed = startupbs.Nome, UserId = db.User.Where(u => u.email == user.email).FirstOrDefault().UserId });
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public ActionResult UpdateSheet()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Update()
        {
            ViewBag.Nome = user.nome.ToString();
            ViewBag.UserId = user.UserId;

            var file = Request.Files[0];
            var fileName = Path.GetFileName(file.FileName);

            Excel.Workbook MyBook = null;
            Excel.Application MyApp = null;
            Excel.Worksheet MySheet = null;
            MyApp = new Excel.Application();
            MyApp.Visible = false;
            MyBook = MyApp.Workbooks.Open(fileName);
            MySheet = (Excel.Worksheet)MyBook.Sheets[1];
            var lastRow = MySheet.Cells.SpecialCells(Excel.XlCellType.xlCellTypeLastCell).Row;

            
            BindingList<Startupbs> EmpList = new BindingList<Startupbs>();
            for (int index = 2; index <= lastRow; index++)
            {
                Array MyValues = (Array)MySheet.get_Range("A" +
                   index.ToString(), "D" + index.ToString()).Cells.Value;
                var stat = MyValues.GetValue(1, 3).ToString();
                int statID = 3;
                switch (stat)
                {
                    case "Active":
                        statID = 3;
                        break;
                    case "Declined":
                        statID = 12;
                        break;
                    case "Deleted":
                        statID = 9;
                        break;
                    case "Graduated":
                        statID = 10;
                        break;
                    case "Suspended":
                        statID = 11;
                        break;
                    default:
                        break;
                }
                EmpList.Add(new Startupbs
                {
                    Nome = MyValues.GetValue(1, 1).ToString(),
                    BizSparkID = MyValues.GetValue(1, 2).ToString(),

StartupCentral/Views/Startupbs/Delete.cshtml
@model StartupCentral.Models.Startupbs

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutGL.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Startupbs</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aceleradora.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aceleradora.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beneficio.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beneficio.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MicrosoftAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MicrosoftAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BizSparkID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BizSparkID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumoMes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumoMes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumoAcumulado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumoAcumulado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumoPago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumoPago)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StartupCentral/Views/Startupbs/Index.cshtml
@model IEnumerable<StartupCentral.Models.Startupbs>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutGL.cshtml";
    bool lineColor = true;
}

<div class="col-md-12 col-sm-12 col-xs-12" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Lista de Contatos</h3>
            </div>
            @using (Html.BeginForm("Index", "Startupbs", FormMethod.Post))
            {
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                           @Html.TextBox("SearchString", "" ,new { @class = "form-control", placeholder = "Digite aqui" })
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">Go!</button>
                            </span>
                    </div>
                </div>
            </div>
            }
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Lista de Startups <small>Startups BizSpark Brasil</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                @Html.ActionLink("Adicionar Nova", "Create")
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table bulk_action">
                                <thead>
                                    <tr class="headings">
                                        @*<th>
                                                <input type="checkbox" id="check-all" class="flat">
                                            </th>*@
                                        <th class="column-title">Nome </th>
                                        <th class="column-title">Email </th>
                                        <th class="column-title">Microsoft Account </th>
                                        <th class="column-title">BizSpark ID </th>
                                        <th class="column-title">Aceleradora </th>
                                        <th class="column-title">Benefício </th>
                                        <th class="column-title">Status </th>
                                        <th class="column-title">Consumo Mês </th>
                                        <th class="column-title">Consumo Acumulado </th>
                                        <th class="column-title">Consumo Pago </th>
                                        <th class="column-title">Owner </th>
                                        <th class="column-title no-link last">
                                            <span class="nobr">Action</span>
                                        </th>
                                        <th class="bulk-actions" colspan="11">
                                            <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        if (lineColor)
                                        {
                                            lineColor = !lineColor;
                                            <tr class="even pointer">
                                                @*<td class="a-center ">
                                                        <input type="checkbox" class="flat" name="table_records">
                                                    </td>*@
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Nome)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Email)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.MicrosoftAccount)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.BizSparkID)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Aceleradora.Nome)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Beneficio.Nome)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Status.Nome)</td>
                                                <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.ConsumoMes)</td>
                                                <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.ConsumoAcumulado)</td>
                                                <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.ConsumoPago)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Owner)</td>
                                                <td class=" last">
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.StartupbsId }) |
                                                    @Html.ActionLink("Details", "Details", new { id = item.StartupbsId }) |
                                                    @Html.ActionLink("Delete", "Delete", new { id = item.StartupbsId })
                                                </td>
                                            </tr>
                                        }
                                        else
                                        {
                                            lineColor = !lineColor;
                                            <tr class="odd pointer">
                                                @*<td class="a-center ">
                                                        <input type="checkbox" class="flat" name="table_records">
                                                    </td>*@
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Nome)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Email)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.MicrosoftAccount)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.BizSparkID)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Aceleradora.Nome)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Beneficio.Nome)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Status.Nome)</td>
                                                <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.ConsumoMes)</td>
                                                <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.ConsumoAcumulado)</td>
                                                <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.ConsumoPago)</td>
                                                <td class=" ">@Html.DisplayFor(modelItem => item.Owner)</td>
                                                <td class=" last">
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.StartupbsId }) |
                                                    @Html.ActionLink("Details", "Details", new { id = item.StartupbsId }) |
                                                    @Html.ActionLink("Delete", "Delete", new { id = item.StartupbsId })
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <!-- FastClick -->
        <script src="../vendors/fastclick/lib/fastclick.js"></script>
        <!-- iCheck -->
        <script src="~Content/vendors/iCheck/icheck.min.js"></script>
    }

StartupCentral/Views/Startupbs/UpdateSheet.cshtml
@model StartupCentral.Models.Startupbs

@{
    ViewBag.Title = "UpdateSheet";
    Layout = "~/Views/Shared/_LayoutGL.cshtml";
}

<!-- page content -->
<div class="col-md-12 col-sm-12 col-xs-12" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Form Upload </h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Carregue uma planilha excel com os consumos.</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <p>Arraste e solte a planilha aqui ou clique para selecionar um arquivo no seu computador.</p>
                        <form method="post" action="@Url.Action("Update", "Startupbs")" class="dropzone"></form>
                        <br />
                        <br />
                        <br />
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/vendors/dropzone/dist/min/dropzone.min.js"></script>
}